### PR TITLE
New iconography for rebrand and persisting code points

### PR DESCRIPTION
**Pull request by jamesseanwright**
As Sky News is undergoing a slight rebrand, we have been required to update some of the existing Skycons and add new ones for YouTube, Vine, and Instagram. According to one of the designers in News, the updated icons are part of a rebrand that will affect the main Sky websites, thus I am creating this pull request.

Additionally, in the project's gulpfile I have set gulp-iconfont's `appendCodepoints` property to `true`, which leaves any existing character code points unchanged. This is useful for us as we use Browserify, thus we are including Skycons manually.

It would be great if someone outside of Sky News could review this, to ensure that the changes will bode well elsewhere. That said, I will package these changes as a new major release upon this being accepted, thus allowing legacy updates to be made to the current 0.x version.

Let me know if you have any questions or an alternative versioning approach.

Cheers,
James

### CODE REVIEW

**Comment by ekynoxe** [comment]
@rosswarren @damnhipster @DanForys @fraserYT @georgerichmond @skycom Since you have all forked the repo at some point, do you have any input on this issue?

Thanks

**Comment by rosswarren** [comment]
@jonathan-hodgson is working on the new icon font with the full set of new icons.

Could you join the skycons channel on Slack? Kathy Kavan is on there who is providing the full SVG set.

**Comment by ekynoxe** [comment]
Thanks @rosswarren we're in slack and talking about it. Seems that there's been some comms breakages between designers in news and others. We had assumed that the icons we received had been vetted at a more global level.

**Comment by jamesseanwright** [comment]
Closing this as the upcoming update to Skycons will include the icons we need. To continue with our rebrand, we'll use our custom fork for now and then integrate with the new release for parity's sake. Cheers!

**Pull request closed without merging**
